# hyper parameters settings
epochs: 300
lrG: 1.e-5
lrD: 1.e-5
batch_size: 4
num_workers: 5
shuffle: true
pin_memory: true
resnet: resnet34
sin_valid: 1
gammaG:  0.1
gammaD:  0.1
sigma: 3
devices:
  # - 0
  - 1
  - 2
  # - 3
  # - 4
  # - 5
  # - 6
  # - 7

# dataset settings
dataset: hela
train_path: /data/cwj/data/HeLa/img
label_path: null
suffix: tif

# checkpoint and visualize settings
saver_enable: false
saver_dir: storages
summary_dir: runs
disp_images: 4
v_freq: 100

# image settings
image_x: 512
image_y: 512
dim: 2
image_chan: 1

# resume settings
resume: false
resume_best: true
resume_latest: false
resume_epoch: null

# runtime settings
runtime_id: null
force: false